### ISSUE TITLE
[Safari] The Test Definition creation action tries to POST to "/proctor/definition/{testName}/edit"

### ISSUE THREAD

**Issue by benmyerson** [indeedeng/proctor-webapp-library#3]
In Safari browser on mac osx 10.11, the test creation form action reports as  "/proctor/definition/{testName}/edit" rather than the "/proctor/definition/%7BtestName%7D/edit" other browsers show.  Line [220 of editor.js](https://github.com/indeedeng/proctor-webapp-library/blob/3d678fcb50f5916e15e8af4a3b0aa29a79d9acd0/src/main/resources/META-INF/resources/static/scripts/app/editor.js#L220-L221) then returns "/proctor/definition/{testName}/edit" for all cases.

**Comment by adamesque** [comment]
FWIW this is due to a webkit bug, which I've reported here: https://bugs.webkit.org/show_bug.cgi?id=157153

**Comment by YiqingIndeed** [comment]
Fixed
